//SELECTIONNER LES ELEMENTS DANS LE DOM


//PSEUDO CODE

//AU CLIC BOUTON NEWGAME ADDEVENTLISTENER
//LES CORES SONT REINITIALISES

//AU CLIC BOUTON HOLD
// - LES POINTS ROUND --> GLOBAL
// - TOUR DE L AUTRE JOUEUR changement de couleur de fonds + point rouge a modifier a cote de "joueur"

//AU CLIC BOUTON  ROLLEDICE
// - UN NOMBRE ALLEATOIRE EST GENERE PAR LE DE MATHFLOORRANDOM + switch pour affichage face du dé
// - UNE ANIMATION DU DE EST LANCEE

//LORSQUE LE DE DONNE 1
// - LE SCORE ROUND EST REINITIALISE
// - TOUR DE L AUTRE JOUEUR : changement de couleur de fonds + point rouge a modifier a cote de "joueur"

//LORSQU 1 JOUEUR GLOBAL = 100
// UNE NOTIFICATION SE DECLENCHE
// IL N EST PAS POSSIBLE DE CONTINUER A JOUER

